<?php if (count($this->paginator)):?>
    <table>
        <tr>
            <th>Користувач</th>
            <th>Запитання</th>
            <th>Кількість відповідей</th>
        </tr>
        <?php foreach ($this->paginator as $item):?>
        <tr>
            <td><?php echo $item['username'];?></td>
            <td><?php echo $item['title'];?></td>
            <td><?php echo $item['answers_count'];?></td>
        </tr>
        <?php endforeach;?>
        </table>

<!--панель навігації по сторінках
     Sliding - це вид навігації
     partials/my_paginator.phtml - вивід на екран-->
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 
                                'partials/my_paginator.phtml');?>
<?php else:?>
    <p>Питань нема.</p>
<?php endif; ?>



