<?php
//якщо в масиві (повертає фу-я getAllUsers()в моделі)тобто в табл. є дані
if(count($this->users)):?>
    <table>
        <tr>
            <th>ID</th>
            <th>UserName</th>
            <th>Email</th>
            <th>Activated</th>
            <th>Actions</th>
        </tr>
        <?php foreach ($this->users as $user):?>
        <tr>
            <td><?php echo $user->id;?></td>
            <td>
                <a href="<?php echo $this->url(
                                            array('controller'=>'users',
                                                  'action'=> 'view',
                                                  'id'=>$user->id)); 
                            ?>"><?php //гіперсилка для перегляду даних юзера
                                echo $user->username;?></a>
                
                
                </td>
            <td><?php echo $user->email; ?></td>
            <td><?php echo $user->activated;?></td>
                
            <td>
                <a href="<?php echo $this->url(
                                            array('controller'=>'users',
                                                  'action'=> 'edit',
                                                  'id'=>$user->id)); 
                            ?>">Edit</a>
                <a href="<?php echo $this->url(
                                            array('controller'=>'users',
                                                  'action'=> 'delete',
                                                  'id'=>$user->id)); 
                            ?>">Delete</a>
                
            </td>
        </tr>
        
        
        <?php endforeach; ?>
    </table>





    <?php else: ?>
    <p> Користувачів ще немає</p>
    

<?php endif;?>
<a href="<?php echo $this->url(array(
                                        'controller'=>'users',
                                        'action'=>'add'));
            ?>">Добавити нового користувача</a>
